set_property PACKAGE_PIN R2 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]

set_property PACKAGE_PIN C8 [get_ports led_1]
set_property IOSTANDARD LVCMOS33 [get_ports led_1]
set_property PACKAGE_PIN D8 [get_ports led_2]
set_property IOSTANDARD LVCMOS33 [get_ports led_2]

#set_property PACKAGE_PIN H18 [get_ports reset_n]
#set_property IOSTANDARD LVCMOS33 [get_ports reset_n]

set_property PACKAGE_PIN B14 [get_ports LCD_RS]
set_property IOSTANDARD LVCMOS33 [get_ports LCD_RS]

set_property PACKAGE_PIN A13 [get_ports LCD_CS]
set_property IOSTANDARD LVCMOS33 [get_ports LCD_CS]

set_property PACKAGE_PIN C13 [get_ports LCD_WR]
set_property IOSTANDARD LVCMOS33 [get_ports LCD_WR]

set_property PACKAGE_PIN C14 [get_ports LCD_RESET]
set_property IOSTANDARD LVCMOS33 [get_ports LCD_RESET]

set_property PACKAGE_PIN G15 [get_ports LCD_BL]
set_property IOSTANDARD LVCMOS33 [get_ports LCD_BL]

set_property PACKAGE_PIN B15 [get_ports LCD_RDX]
set_property IOSTANDARD LVCMOS33 [get_ports LCD_RDX]

set_property PACKAGE_PIN B16 [get_ports {LCD_DATA[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_DATA[0]}]
set_property PACKAGE_PIN A14 [get_ports {LCD_DATA[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_DATA[1]}]
set_property PACKAGE_PIN B17 [get_ports {LCD_DATA[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_DATA[2]}]
set_property PACKAGE_PIN A15 [get_ports {LCD_DATA[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_DATA[3]}]
set_property PACKAGE_PIN D15 [get_ports {LCD_DATA[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_DATA[4]}]
set_property PACKAGE_PIN C16 [get_ports {LCD_DATA[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_DATA[5]}]
set_property PACKAGE_PIN E15 [get_ports {LCD_DATA[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_DATA[6]}]
set_property PACKAGE_PIN A17 [get_ports {LCD_DATA[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_DATA[7]}]
set_property PACKAGE_PIN G16 [get_ports {LCD_DATA[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_DATA[8]}]
set_property PACKAGE_PIN D16 [get_ports {LCD_DATA[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_DATA[9]}]
set_property PACKAGE_PIN H16 [get_ports {LCD_DATA[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_DATA[10]}]
set_property PACKAGE_PIN E16 [get_ports {LCD_DATA[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_DATA[11]}]
set_property PACKAGE_PIN C18 [get_ports {LCD_DATA[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_DATA[12]}]
set_property PACKAGE_PIN F15 [get_ports {LCD_DATA[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_DATA[13]}]
set_property PACKAGE_PIN E17 [get_ports {LCD_DATA[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_DATA[14]}]
set_property PACKAGE_PIN C17 [get_ports {LCD_DATA[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_DATA[15]}]

#keyboard start
set_property PACKAGE_PIN A12 [get_ports {row_data_in[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {row_data_in[0]}]
set_property PACKAGE_PIN B11 [get_ports {row_data_in[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {row_data_in[1]}]
set_property PACKAGE_PIN D10 [get_ports {row_data_in[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {row_data_in[2]}]
set_property PACKAGE_PIN D9 [get_ports {row_data_in[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {row_data_in[3]}]

set_property PACKAGE_PIN D14 [get_ports {col_data_out[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {col_data_out[0]}]
set_property PACKAGE_PIN D13 [get_ports {col_data_out[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {col_data_out[1]}]
set_property PACKAGE_PIN C12 [get_ports {col_data_out[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {col_data_out[2]}]
set_property PACKAGE_PIN E13 [get_ports {col_data_out[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {col_data_out[3]}]

set_property PULLUP true [get_ports {row_data_in[0]}]
set_property PULLUP true [get_ports {row_data_in[1]}]
set_property PULLUP true [get_ports {row_data_in[2]}]
set_property PULLUP true [get_ports {row_data_in[3]}]
set_property DRIVE 8 [get_ports {col_data_out[*]}]
set_property SLEW SLOW [get_ports {col_data_out[*]}]
#keyboard end

#set_property PACKAGE_PIN F14 [get_ports {la_out[0]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {la_out[0]}]
#set_property PACKAGE_PIN B12 [get_ports {la_out[1]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {la_out[1]}]
#set_property PACKAGE_PIN C11 [get_ports {la_out[2]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {la_out[2]}]
#set_property PACKAGE_PIN D11 [get_ports {la_out[3]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {la_out[3]}]
#set_property PACKAGE_PIN C9 [get_ports {la_out[4]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {la_out[4]}]
#set_property PACKAGE_PIN A10 [get_ports {la_out[5]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {la_out[5]}]
#set_property PACKAGE_PIN A9 [get_ports {la_out[6]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {la_out[6]}]
#set_property PACKAGE_PIN B10 [get_ports {la_out[7]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {la_out[7]}]


set_property PULLTYPE PULLUP [get_ports {col_data_out[3]}]
set_property PULLTYPE PULLUP [get_ports {col_data_out[2]}]
set_property PULLTYPE PULLUP [get_ports {col_data_out[1]}]
set_property PULLTYPE PULLUP [get_ports {col_data_out[0]}]


#set_property PACKAGE_PIN E8 [get_ports {spi_sclk}]
#set_property IOSTANDARD LVCMOS33 [get_ports {spi_sclk}]
#set_property PACKAGE_PIN L15 [get_ports {spi_cs_n}]
#set_property IOSTANDARD LVCMOS33 [get_ports {spi_cs_n}]
#set_property PACKAGE_PIN K16 [get_ports {spi_dq[0]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {spi_dq[0]}]
#set_property PACKAGE_PIN L17 [get_ports {spi_dq[1]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {spi_dq[1]}]
#set_property PACKAGE_PIN J15 [get_ports {spi_dq[2]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {spi_dq[2]}]
#set_property PACKAGE_PIN J16 [get_ports {spi_dq[3]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {spi_dq[3]}]

set_property PACKAGE_PIN K16 [get_ports {spi_mosi}]
set_property IOSTANDARD LVCMOS33 [get_ports {spi_mosi}]
set_property PACKAGE_PIN L17 [get_ports {spi_miso}]
set_property IOSTANDARD LVCMOS33 [get_ports {spi_miso}]

set_property PACKAGE_PIN G17 [get_ports {ts_clk}]
set_property IOSTANDARD LVCMOS33 [get_ports {ts_clk}]
set_property PACKAGE_PIN F18 [get_ports {ts_cs}]
set_property IOSTANDARD LVCMOS33 [get_ports {ts_cs}]
set_property PACKAGE_PIN D18 [get_ports {ts_pen}]
set_property IOSTANDARD LVCMOS33 [get_ports {ts_pen}]
set_property PACKAGE_PIN E18 [get_ports {ts_miso}]
set_property IOSTANDARD LVCMOS33 [get_ports {ts_miso}]
set_property PACKAGE_PIN F17 [get_ports {ts_mosi}]
set_property IOSTANDARD LVCMOS33 [get_ports {ts_mosi}]


#
# SDRAM signals
#
set_property PACKAGE_PIN P16 [get_ports SDRAM_CLK]
set_property IOSTANDARD LVCMOS33 [get_ports SDRAM_CLK]
set_property PACKAGE_PIN R16 [get_ports SDRAM_CKE]
set_property IOSTANDARD LVCMOS33 [get_ports SDRAM_CKE]

set_property PACKAGE_PIN N16 [get_ports SDRAM_DQM[1]]
set_property IOSTANDARD LVCMOS33 [get_ports SDRAM_DQM[1]]
set_property PACKAGE_PIN V16 [get_ports SDRAM_DQM[0]]
set_property IOSTANDARD LVCMOS33 [get_ports SDRAM_DQM[0]]

set_property PACKAGE_PIN U14 [get_ports SDRAM_CASn]
set_property IOSTANDARD LVCMOS33 [get_ports SDRAM_CASn]
set_property PACKAGE_PIN V14 [get_ports SDRAM_RASn]
set_property IOSTANDARD LVCMOS33 [get_ports SDRAM_RASn]
set_property PACKAGE_PIN U15 [get_ports SDRAM_WEn]
set_property IOSTANDARD LVCMOS33 [get_ports SDRAM_WEn]
set_property PACKAGE_PIN V13 [get_ports SDRAM_CSn]
set_property IOSTANDARD LVCMOS33 [get_ports SDRAM_CSn]

set_property PACKAGE_PIN U12 [get_ports SDRAM_BA[1]]
set_property IOSTANDARD LVCMOS33 [get_ports SDRAM_BA[1]]
set_property PACKAGE_PIN V12 [get_ports SDRAM_BA[0]]
set_property IOSTANDARD LVCMOS33 [get_ports SDRAM_BA[0]]

set_property PACKAGE_PIN P15 [get_ports SDRAM_A[12]]
set_property IOSTANDARD LVCMOS33 [get_ports SDRAM_A[12]]
set_property PACKAGE_PIN R15 [get_ports SDRAM_A[11]]
set_property IOSTANDARD LVCMOS33 [get_ports SDRAM_A[11]]
set_property PACKAGE_PIN V11 [get_ports SDRAM_A[10]]
set_property IOSTANDARD LVCMOS33 [get_ports SDRAM_A[10]]
set_property PACKAGE_PIN T15 [get_ports SDRAM_A[9]]
set_property IOSTANDARD LVCMOS33 [get_ports SDRAM_A[9]]
set_property PACKAGE_PIN P14 [get_ports SDRAM_A[8]]
set_property IOSTANDARD LVCMOS33 [get_ports SDRAM_A[8]]
set_property PACKAGE_PIN T14 [get_ports SDRAM_A[7]]
set_property IOSTANDARD LVCMOS33 [get_ports SDRAM_A[7]]
set_property PACKAGE_PIN T13 [get_ports SDRAM_A[6]]
set_property IOSTANDARD LVCMOS33 [get_ports SDRAM_A[6]]
set_property PACKAGE_PIN R13 [get_ports SDRAM_A[5]]
set_property IOSTANDARD LVCMOS33 [get_ports SDRAM_A[5]]
set_property PACKAGE_PIN T12 [get_ports SDRAM_A[4]]
set_property IOSTANDARD LVCMOS33 [get_ports SDRAM_A[4]]
set_property PACKAGE_PIN U9 [get_ports SDRAM_A[3]]
set_property IOSTANDARD LVCMOS33 [get_ports SDRAM_A[3]]
set_property PACKAGE_PIN V9 [get_ports SDRAM_A[2]]
set_property IOSTANDARD LVCMOS33 [get_ports SDRAM_A[2]]
set_property PACKAGE_PIN U10 [get_ports SDRAM_A[1]]
set_property IOSTANDARD LVCMOS33 [get_ports SDRAM_A[1]]
set_property PACKAGE_PIN U11 [get_ports SDRAM_A[0]]
set_property IOSTANDARD LVCMOS33 [get_ports SDRAM_A[0]]

set_property PACKAGE_PIN P18 [get_ports SDRAM_DQ[0]]
set_property IOSTANDARD LVCMOS33 [get_ports SDRAM_DQ[0]]
set_property PACKAGE_PIN R18 [get_ports SDRAM_DQ[1]]
set_property IOSTANDARD LVCMOS33 [get_ports SDRAM_DQ[1]]
set_property PACKAGE_PIN R17 [get_ports SDRAM_DQ[2]]
set_property IOSTANDARD LVCMOS33 [get_ports SDRAM_DQ[2]]
set_property PACKAGE_PIN T18 [get_ports SDRAM_DQ[3]]
set_property IOSTANDARD LVCMOS33 [get_ports SDRAM_DQ[3]]
set_property PACKAGE_PIN T17 [get_ports SDRAM_DQ[4]]
set_property IOSTANDARD LVCMOS33 [get_ports SDRAM_DQ[4]]
set_property PACKAGE_PIN U17 [get_ports SDRAM_DQ[5]]
set_property IOSTANDARD LVCMOS33 [get_ports SDRAM_DQ[5]]
set_property PACKAGE_PIN V17 [get_ports SDRAM_DQ[6]]
set_property IOSTANDARD LVCMOS33 [get_ports SDRAM_DQ[6]]
set_property PACKAGE_PIN U16 [get_ports SDRAM_DQ[7]]
set_property IOSTANDARD LVCMOS33 [get_ports SDRAM_DQ[7]]
set_property PACKAGE_PIN N17 [get_ports SDRAM_DQ[8]]
set_property IOSTANDARD LVCMOS33 [get_ports SDRAM_DQ[8]]
set_property PACKAGE_PIN N18 [get_ports SDRAM_DQ[9]]
set_property IOSTANDARD LVCMOS33 [get_ports SDRAM_DQ[9]]
set_property PACKAGE_PIN M16 [get_ports SDRAM_DQ[10]]
set_property IOSTANDARD LVCMOS33 [get_ports SDRAM_DQ[10]]
set_property PACKAGE_PIN M17 [get_ports SDRAM_DQ[11]]
set_property IOSTANDARD LVCMOS33 [get_ports SDRAM_DQ[11]]
set_property PACKAGE_PIN K17 [get_ports SDRAM_DQ[12]]
set_property IOSTANDARD LVCMOS33 [get_ports SDRAM_DQ[12]]
set_property PACKAGE_PIN L18 [get_ports SDRAM_DQ[13]]
set_property IOSTANDARD LVCMOS33 [get_ports SDRAM_DQ[13]]
set_property PACKAGE_PIN K18 [get_ports SDRAM_DQ[14]]
set_property IOSTANDARD LVCMOS33 [get_ports SDRAM_DQ[14]]
set_property PACKAGE_PIN J18 [get_ports SDRAM_DQ[15]]
set_property IOSTANDARD LVCMOS33 [get_ports SDRAM_DQ[15]]


set_property IOSTANDARD LVCMOS33 [get_ports DAC_DATA[0]]
set_property IOSTANDARD LVCMOS33 [get_ports DAC_DATA[1]]
set_property IOSTANDARD LVCMOS33 [get_ports DAC_DATA[2]]
set_property IOSTANDARD LVCMOS33 [get_ports DAC_DATA[3]]
set_property IOSTANDARD LVCMOS33 [get_ports DAC_DATA[4]]
set_property IOSTANDARD LVCMOS33 [get_ports DAC_DATA[5]]
set_property IOSTANDARD LVCMOS33 [get_ports DAC_DATA[6]]
set_property IOSTANDARD LVCMOS33 [get_ports DAC_DATA[7]]
set_property IOSTANDARD LVCMOS33 [get_ports DAC_DATA[8]]
set_property IOSTANDARD LVCMOS33 [get_ports DAC_DATA[9]]
set_property IOSTANDARD LVCMOS33 [get_ports DAC_DATA[10]]
set_property IOSTANDARD LVCMOS33 [get_ports DAC_DATA[11]]
set_property IOSTANDARD LVCMOS33 [get_ports DAC_DATA[12]]
set_property IOSTANDARD LVCMOS33 [get_ports DAC_DATA[13]]

set_property IOSTANDARD LVCMOS33 [get_ports DAC_CLK]


set_property PACKAGE_PIN K5 [get_ports DAC_DATA[0]]
set_property PACKAGE_PIN R1 [get_ports DAC_DATA[2]]
set_property PACKAGE_PIN N2 [get_ports DAC_DATA[4]]
set_property PACKAGE_PIN M1 [get_ports DAC_DATA[6]]
set_property PACKAGE_PIN J4 [get_ports DAC_DATA[8]]
set_property PACKAGE_PIN K6 [get_ports DAC_DATA[10]]
set_property PACKAGE_PIN L3 [get_ports DAC_DATA[12]]
set_property PACKAGE_PIN K1 [get_ports DAC_CLK]

set_property PACKAGE_PIN P1 [get_ports DAC_DATA[1]]
set_property PACKAGE_PIN N1 [get_ports DAC_DATA[3]]
set_property PACKAGE_PIN M2 [get_ports DAC_DATA[5]]
set_property PACKAGE_PIN J5 [get_ports DAC_DATA[7]]
set_property PACKAGE_PIN J6 [get_ports DAC_DATA[9]]
set_property PACKAGE_PIN L2 [get_ports DAC_DATA[11]]
set_property PACKAGE_PIN K2 [get_ports DAC_DATA[13]]


set_property SLEW FAST [get_ports {DAC_DATA[*]}]
set_property SLEW FAST [get_ports DAC_CLK]
set_property DRIVE 16 [get_ports {DAC_DATA[*]}]
set_property DRIVE 16 [get_ports DAC_CLK]

set_property PACKAGE_PIN V8 [get_ports adc_ch1[0]]
set_property PACKAGE_PIN U7 [get_ports adc_ch1[2]]
set_property PACKAGE_PIN T7 [get_ports adc_ch1[4]]
set_property PACKAGE_PIN R6 [get_ports adc_ch1[6]]
set_property PACKAGE_PIN R5 [get_ports adc_ch1[8]]
set_property PACKAGE_PIN U6 [get_ports adc_ch1[10]]

set_property PACKAGE_PIN V7 [get_ports adc_clk_out1]
set_property PACKAGE_PIN V6 [get_ports adc_ch1[1]]
set_property PACKAGE_PIN R7 [get_ports adc_ch1[3]]
set_property PACKAGE_PIN T5 [get_ports adc_ch1[5]]
set_property PACKAGE_PIN T4 [get_ports adc_ch1[7]]
set_property PACKAGE_PIN U5 [get_ports adc_ch1[9]]
set_property PACKAGE_PIN U4 [get_ports adc_ch1[11]]

set_property PACKAGE_PIN P3 [get_ports adc_ch2[0]]
set_property PACKAGE_PIN M5 [get_ports adc_ch2[2]]
set_property PACKAGE_PIN L4 [get_ports adc_ch2[4]]
set_property PACKAGE_PIN T2 [get_ports adc_ch2[6]]
set_property PACKAGE_PIN T3 [get_ports adc_ch2[8]]
set_property PACKAGE_PIN U1 [get_ports adc_ch2[10]]

set_property PACKAGE_PIN N4 [get_ports adc_clk_out2]
set_property PACKAGE_PIN M6 [get_ports adc_ch2[1]]
set_property PACKAGE_PIN L5 [get_ports adc_ch2[3]]
set_property PACKAGE_PIN R3 [get_ports adc_ch2[5]]
set_property PACKAGE_PIN P4 [get_ports adc_ch2[7]]
set_property PACKAGE_PIN U2 [get_ports adc_ch2[9]]
set_property PACKAGE_PIN V3 [get_ports adc_ch2[11]]

set_property IOSTANDARD LVCMOS33 [get_ports {adc_ch1[*]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_ch2[*]}]    
set_property IOSTANDARD LVCMOS33 [get_ports {adc_clk_out1}]    
set_property IOSTANDARD LVCMOS33 [get_ports {adc_clk_out2}]    